import "dart:ffi";
import "dart:io";
import "dart:typed_data";

import "../generated/librealsense_ffi_bindings.dart";
export "../generated/librealsense_ffi_bindings.dart";

extension NativeFramesUtils on Pointer<NativeFrames> {
  void dispose() {
    if (this == nullptr) return;
    print("Disposing frame: $this");
    realsenseLib.NativeFrames_free(this);
  }

  Uint8List get depthFrame {
    final NativeFrames struct = ref;
    return struct.depth_data.asTypedList(struct.depth_length);
  }

  Uint8List get colorizedFrame {
    final NativeFrames struct = ref;
    return struct.colorized_data.asTypedList(struct.colorized_length);
  }

  bool get isEmpty => this == nullptr;
}

String _getPath() {
  if (Platform.isWindows) {
    return "realsense_ffi.dll";
  } else if (Platform.isMacOS) {
    return "opencv_ffi.dylib";
  } else if (Platform.isLinux) {
    return "realsense_ffi.so";
  } else {
    throw UnsupportedError("Unsupported platform");
  }
}

/// The C bindings generated by `package:ffigen`.
final realsenseLib = LibRealSenseBindings(DynamicLibrary.open(_getPath()));
