
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Aldre/scoop/apps/cmake/3.29.3/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
