name: Dart Analyzer

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1

      # This package is part of a Pub Workspace. However, CI still needs to
      # run on this repo by itself, so we want to override burt_network to use
      # a Git dependency ONLY on GitHub Actions.
      #
      # To get around this, we commit the overrides to the .github folder where
      # Dart can't find them, then copy them as part of the CI workflow.
      - name: Install dependencies
        run: |
          mv .github/pubspec_overrides.yaml .
          dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test
